name: Release

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: docker build . -t benquis/node-app-github-actions-crashcourse
      - run: echo "${{secrets.DOCKER_PASSWD}}" | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
      - run: docker push benquis/node-app-github-actions-crashcourse